version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.12
    working_directory: /tmp/cosmos-gen
jobs: 
  build:
    executor: go
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v3-{{ checksum "go.sum" }}
      - run: make install-tools-linux
      - run: make lint
      - run: make build-linux
      - run:
          name: List built binaries
          command: |
            pwd
            ls -l cosmos-gen
      - save_cache:
          key: go-mod-v3-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: .
          paths:
            - cosmos-gen
  test:
    executor: go
    steps:
      - attach_workspace:
          at: /tmp/cosmos-gen
      - run:
          name: Run test
          command: |
            ./cosmos-gen claim
      - run:
          name: List generated files
          command: |
            pwd
            ls -l ./x/claim/
workflows:
  build-flow:
    jobs:
      - build
      - test:
          requires:
            - build


