version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.12
    working_directory: /tmp/cosmos-gen
jobs: 
  build:
    executor: go
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v3-{{ checksum "go.sum" }}
      - run:
          name: Install linter
          command: |
            GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@692dacb773b703162c091c2d8c59f9cd2d6801db
      - run: make build-linux
      - run:
          name: List built binaries
          command: |
            pwd
            ls -l ./bin/
      - save_cache:
          key: go-mod-v3-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - persist_to_workspace:
          root: bin
          paths:
            - cosmos-gen
  test:
    executor: go
    steps:
      - attach_workspace:
          at: /tmp/cosmos-gen/bin
      - run:
          name: Run test
          command: |
            ./bin/cosmos-gen claim
      - run:
          name: List generated files
          command: |
            pwd
            ls -l ./x/claim/
workflows:
  build-flow:
    jobs:
      - build
      - test:
          requires:
            - build


